---
- hosts: localhost

  pre_tasks:
    - name: "Include locals vars"
      include_vars:
        file: "locals.yaml"
      tags: always

  roles:
    - role: docker
      become: true
      tags: docker
    - role: sourcejedi.rpmfusion_free
      become: true
      tags: rpm
    - role: fedora_dependencies
      become: true
      tags: fedora_dependencies
    - role: donhector.workstation.asdf
      tags: asdf
    - role: hostname
      become: true
      tags: hostname
    - role: jaredhocutt.gnome_extensions
      tags: gnome_extensions
    - role: git_config
      tags: git_config
    - role: kdrive
      tags: kdrive
    - role: jetbrains_toolbox
      tags: jetbrains_toolbox
    - role: gnome
      tags: gnome
    - role: commons
      tags: commons
